services:
  app1:
    build:
      context: ./app1
    ports:
      - "8081:8081"

  app2:
    build:
      context: ./app2
    ports:
      - "8082:8082"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - prometheus
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  k6:
    build:
      context: ./k6
      dockerfile: Dockerfile
    depends_on:
      - nginx
    ports:
      - "6565:6565"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - nginx-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    command:
      - '-nginx.scrape-uri=http://nginx/metrics'

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./nginx_logs:/var/log/nginx
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki     